language: java
jdk:
  - oraclejdk11
addons:
  sonarcloud:
    organization: "cy6ergn0m-jj-feb-21"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=cy6erGn0m_jj-feb-2021
